name: Deploy Infrastructure using OIDC

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::767397768705:role/New-Role-GITHUB-AWS
          aws-region: ap-south-1

      - name: Deploy with Terraform
        run: |
          terraform init
          terraform apply -auto-approve
